### ISSUE TITLE
Browsing through the code... does bank4 need to be handled as a case in ItemChecklistPlayer.cs?

### ISSUE THREAD

**Issue by DaLynxx** [JavidPack/ItemChecklist#12]
I have never programmed a terraria mod... so my comment may not be a potential bug at all. Howerver, I find the prospect of this mod to be intriguing in a "got to catch them all kind of way"...

https://github.com/JavidPack/ItemChecklist/blob/a99a659b003fffc9e609e986226e15a20adc11a6/ItemChecklistPlayer.cs#L116-L130

Assuming that the "banks" covers different extra storage tied to the player, such as Piggybank, Safe, Void and Defenders forge. Not sure which one is chich though. But the "if cases felt" incomplete compared to the number of banks defined for a player.

(ref: https://docs.tmodloader.net/html_alpha/class_terraria_1_1_player.html)

**Comment by JavidPack** [comment]
yeah, it'll need to be added before release.
