### ISSUE TITLE
Show whether an item is ever crafted

### ISSUE THREAD

**Issue by Kimi-Arthur** [JavidPack/ItemChecklist#2]
Even though we know what item are found by us, we don't know whether we only picked it up? Or we actually created them.

_Haven't thought this through, but think this may be interesting._

Maybe when we show the tooltip, we show an extra line (or a glyph / icon) to indicate whether we ever crafted it.

**Comment by JavidPack** [comment]
I don't really see the point of this suggestion, tbh.

**Comment by Kimi-Arthur** [comment]
Not that interesting I guess...
